### ISSUE TITLE
Will there be configuration file support in next release?

### ISSUE THREAD

**Issue by Shumen** [OpenAoE/vblade#8]
Since it's important to support conf-file as a server daemon program, instead of command line arguments.

**Comment by ecashin** [comment]
There is no plan to add that, because the vblade is deliberately minimal.  You'll even notice that the vblade itself always runs in the foreground, and that vbladed is a shell script that daemonizes the vblade.  That separation of concerns is often advocated, e.g., by Dan Bernstein, the author of daemontools.

I can imagine that if a config file was necessary, then one could simply use daemontools (or something like it that is newer, like runit) along with a library like Augeas to build the command line for vblade based on a config file.
